name: CI

# Controls when the action will run. 
on:
  push:
    branches: [ develop ]
    
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  merge-develop-to-master:
    name: Merge master -> develop
    runs-on: ubuntu-latest
    steps:
    - name: automerge
      uses: tukasz/direct-merge-action@master
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        source-branch: develop
        target-branch: main
